environment:

  matrix:
    - TOXENV: "py310"
      PYTHON: "C:\\Python310"

install:
  - "%PYTHON%\\python.exe -m pip install -r dev_requirements.txt"
  - "%PYTHON%\\python.exe -m pip install codecov" 
build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"

on_success:
  - "%PYTHON%\\Scripts\\codecov.exe -f coverage.xml"
